### PR TITLE
Implemented infer script

### PR DESCRIPTION
**Pull request by Zihang-Xia**
Implemented score json function, outputs a dictionary of the original json string, processed vector and anomaly score
replaced rstrip to removesuffix in train.py
```
python infer.py --log-dir /usr/local/Cellar/zeek/6.1.1/logs --model-path kit.joblib 
2024-02-20 02:25:36,868 - root - INFO - Using logdir: /usr/local/Cellar/zeek/6.1.1/logs (infer.py)
2024-02-20 02:25:36,868 - root - INFO - Using spool path: /usr/local/Cellar/zeek/6.1.1/logs/current (infer.py)
2024-02-20 02:25:36,869 - root - INFO - Using model path: kit.joblib (infer.py)
2024-02-20 02:25:40,905 - root - INFO - Hello from preprocess_json. Please implement me :) (utils.py)
{'input_vector': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32), 'anomaly_score': 0.13725296650850127, 'json': '{"ts":1708413879.289559,"uid":"CbRjvXuaOe60POxO6","id.orig_h":"192.168.1.156","id.orig_p":64469,"id.resp_h":"142.250.72.110","id.resp_p":443,"proto":"udp","service":"quic,ssl","duration":0.11581015586853027,"orig_bytes":3660,"resp_bytes":3401,"conn_state":"SF","local_orig":true,"local_resp":false,"missed_bytes":0,"history":"Dd","orig_pkts":9,"orig_ip_bytes":3912,"resp_pkts":9,"resp_ip_bytes":3653}'}
2024-02-20 02:25:47,942 - root - INFO - Hello from preprocess_json. Please implement me :) (utils.py)
{'input_vector': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32), 'anomaly_score': 0.11276509267628576, 'json': '{"ts":1708413941.765467,"uid":"CUWzWr1eltCP5oIU8f","id.orig_h":"192.168.1.156","id.orig_p":58353,"id.resp_h":"43.130.30.247","id.resp_p":80,"proto":"tcp","service":"http","duration":0.4077620506286621,"orig_bytes":753,"resp_bytes":347,"conn_state":"SF","local_orig":true,"local_resp":false,"missed_bytes":0,"history":"ShADadFf","orig_pkts":6,"orig_ip_bytes":1077,"resp_pkts":5,"resp_ip_bytes":615}'}
```

### CODE REVIEW

**Comment by diego-lopez8** [comment]
add 5 tuple (src ip, src port, dest ip, dest port, proto) and uid of zeek log to output only

**Comment by diego-lopez8** [comment]
write output of aforementioned results to `/var/log/anomalies.log`

**Comment by Zihang-Xia** [comment]
The log directory on mac and linux is different so I left it as a file in the local directory for now

**Comment by diego-lopez8** [comment]
LGTM

**Pull request merged**
